### ISSUE TITLE
Call to undefined function array_column()

### ISSUE THREAD

**Issue by Lianzy-Baimiao** [Quarkay/Typecho-SimpleCommentCaptcha#2]
Fatal error: Call to undefined function array_column() in C:\wwwroot\*****\usr\plugins\SimpleCommentCaptcha\Plugin.php on line 356

PHP-54

**Comment by Quarkay** [comment]
PHP版本的原因，需要升级到 >= 5.5.0 版本。
虽然 Typecho 官网写的支持到 PHP5.1 及以上 （[见这里](http://docs.typecho.org/install)） ，但个人建议最好使用 PHP7.0 以上环境。
因为其实际开发中变更很多，且未考虑低版本环境。具体可见相关 PR 如： https://github.com/typecho/typecho/pull/928 

所以相关插件自然也未考虑低版本。
